pipeline {
    agent any
    
    stages {
        stage('build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage("Complete"){
            steps{
                echo 'Job Completed'
            }
        }
    }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
